const test=require('node:test');
const assert=require('node:assert/strict');
const {createHmac}=require('node:crypto');
const {PDFDocument}=require('pdf-lib');
require('./register-typescript.cjs');
const {buildSendLibraryRequest}=require('../src/lib/parchment/send-library-request.ts');
const {createParchmentIntAdapter,PARCHMENT_INT_DELIVERY_URL}=require('../src/lib/parchment/int-adapter.ts');
const {verifyParchmentStatusNotification:verify}=require('../src/lib/parchment/status-notification.ts');
const input=()=>({externalOrderId:'synthetic-order',senderCode:'synthetic-sender',productCode:'synthetic-product',student:{email:'learner@example.invalid',studentId:'synthetic-student',dateOfBirth:'2000-01-01',phone:'555-0100',name:{firstName:'Synthetic',lastName:'Learner'}},recipient:{kind:'email',email:'recipient@example.invalid',name:'Synthetic Recipient'}});
const options=fetch=>({enabled:true,senderCode:'synthetic-sender',productCode:'synthetic-product',allowedEmails:['learner@example.invalid','recipient@example.invalid'],allowedRecipientCodes:['synthetic-recipient','1188180'],accessToken:async()=>'synthetic-token',fetch});
test('strict table codes and request-only mode omit image and recipient code',async()=>{const r=await buildSendLibraryRequest(input());assert.equal(r.product.codeType,'MEMBER_PRODUCT_ID');assert.equal(r.sender.codeType,'PARCHMENT_ID');assert.equal(r.deliveryMethod,'electronic');assert.equal('image'in r,false);assert.equal('code'in r.recipient,false);assert.equal(r.student.phone,'555-0100');});
test('valid PDF delivery and attachments use base64 with explicit decoration',async()=>{const pdf=await PDFDocument.create();pdf.addPage();const bytes=await pdf.save();const r=await buildSendLibraryRequest({...input(),image:{bytes,decorated:false,decorationId:7},attachments:[{bytes,fileName:'signature.pdf'}]});assert.deepEqual(Buffer.from(r.image.payload,'base64'),Buffer.from(bytes));assert.equal(r.image.payloadContentType,'PDF');assert.equal(r.image.decorationId,7);assert.equal(r.attachments[0].fileName,'signature.pdf');});
test('invalid PDF and encoded limit fail before transport',async()=>{for(const bytes of [new Uint8Array([1,2]),new Uint8Array(11_250_001)])await assert.rejects(buildSendLibraryRequest({...input(),image:{bytes,decorated:true}}),/input is invalid/);});
test('required fields, valid calendar DOB, identifiers and decoration are not guessed',async()=>{for(const value of [{...input(),senderCode:''},{...input(),productCode:''},{...input(),student:{...input().student,phone:''}},{...input(),student:{...input().student,dateOfBirth:'2001-02-29'}},{...input(),image:{bytes:new Uint8Array([1]),decorated:false}},{...input(),product:{codeType:'BASE_PRODUCT_NAME',code:'Transcript'}}])await assert.rejects(buildSendLibraryRequest(value),/input is invalid/);});
test('network delivery requires explicit code and AMCAS exact identifiers',async()=>{const r=await buildSendLibraryRequest({...input(),recipient:{kind:'amcas',code:'1188180',aamcId:'01234567',transcriptId:'0123456'}});assert.equal(r.recipient.codeType,'PARCHMENT_ID');assert.equal('email'in r.recipient,false);assert.deepEqual(r.orderOptions,[{name:'amcas_aamc_id',value:'01234567'},{name:'transcript_id',value:'0123456'}]);for(const recipient of [{kind:'network',code:'1188180'},{kind:'amcas',code:'1188180',aamcId:'123',transcriptId:'0123456'}])await assert.rejects(buildSendLibraryRequest({...input(),recipient}),/input is invalid/);});
test('disabled default makes no token or fetch calls',async()=>{let calls=0;const send=createParchmentIntAdapter({...options(async()=>{calls++;}),enabled:undefined,accessToken:async()=>{calls++;return 'token';}});assert.deepEqual(await send(input()),{status:'disabled'});assert.equal(calls,0);});
test('INT adapter preserves accepted vs delivered and binds exact endpoint',async()=>{let calls=0;const send=createParchmentIntAdapter(options(async(url,init)=>{calls++;assert.equal(url,'https://api.int.parchment.com/send-library-api/v1/requestCredentialDelivery');assert.equal(url,PARCHMENT_INT_DELIVERY_URL);assert.equal(init.redirect,'error');assert.equal(init.headers.Authorization,'Bearer synthetic-token');assert.equal(JSON.parse(init.body).externalOrderId,'synthetic-order');return Response.json({AcknowledgmentData:{AcknowledgmentCode:'Accepted',NoteMessage:['Delivered PRIVATE']}});}));assert.deepEqual(await send(input()),{status:'accepted',externalOrderId:'synthetic-order',deliveryVerified:false});assert.equal(calls,1);});
test('INT recipient and learner allowlists plus sender/product enforce config before I/O',async()=>{let calls=0;const o={...options(async()=>{calls++;}),accessToken:async()=>{calls++;return 'token';}};for(const v of [{...input(),senderCode:'other'},{...input(),productCode:'other'},{...input(),student:{...input().student,email:'other@example.invalid'}},{...input(),recipient:{kind:'email',email:'other@example.invalid',name:'Other'}},{...input(),recipient:{kind:'network',code:'other'}},{...input(),recipient:{kind:'amcas',code:'10013',aamcId:'01234567',transcriptId:'0123456'}}])assert.deepEqual(await createParchmentIntAdapter(o)(v),{status:'configuration_error'});assert.equal(calls,0);});
test('ambiguous HTTP/provider failures are unknown and never retried',async()=>{for(const response of [()=>new Response('PRIVATE',{status:500}),()=>Response.json({AcknowledgmentData:{AcknowledgmentCode:'Other'}}),()=>new Response('not json'),()=>{throw Error('PRIVATE token');}]){let calls=0;const result=await createParchmentIntAdapter(options(async()=>{calls++;return response();}))(input());assert.deepEqual(result,{status:'unknown_outcome'});assert.equal(calls,1);assert.equal(JSON.stringify(result).includes('PRIVATE'),false);}});
test('response body is bounded even without content-length',async()=>{const result=await createParchmentIntAdapter(options(async()=>new Response(new ReadableStream({start(c){c.enqueue(new Uint8Array(64_001));c.close();}}))))(input());assert.deepEqual(result,{status:'unknown_outcome'});});
test('late token after timeout cannot start a delivery',async t=>{t.mock.timers.enable({apis:['setTimeout']});let done,calls=0;const send=createParchmentIntAdapter({...options(async()=>{calls++;return Response.json({});}),accessToken:()=>new Promise(resolve=>{done=resolve;})});const pending=send(input());await new Promise(resolve=>setImmediate(resolve));t.mock.timers.tick(10_000);assert.deepEqual(await pending,{status:'configuration_error'});done('late-token');await new Promise(resolve=>setImmediate(resolve));assert.equal(calls,0);});
function event(status='AVAILABLE'){return {event:'order.status.updated',eventTime:'2026-01-01T12:00:00Z',orderLineItem:{documentId:'provider-doc',externalDocumentId:'synthetic-order',status,message:'PRIVATE',sender:{parchmentId:'synthetic-sender'}}};}
function signed(body=event(),encoding='hex'){const rawPayload=Buffer.from(JSON.stringify(body));return {rawPayload,signature:createHmac('sha256','synthetic-secret').update(rawPayload).digest(encoding),secret:'synthetic-secret',signatureEncoding:encoding,expectedExternalOrderId:'synthetic-order',expectedSenderCode:'synthetic-sender',expectedDocumentId:'provider-doc'};}
for(const [provider,status,delivered]of [['PENDING','pending',false],['APPROVED','processing',false],['ERROR','failed',false],['AVAILABLE','available',false],['DELIVERED','delivered',true],['COMPLETE','delivered',true],['CANCELLED','cancelled',false]])test(`verified ${provider} maps truthfully without provider message`,()=>{const r=verify(signed(event(provider)));assert.equal(r.status,status);assert.equal(r.providerReportedDelivery,delivered);assert.equal(r.deliveryVerified,false);assert.equal(r.reconciliationRequired,true);assert.equal(JSON.stringify(r).includes('PRIVATE'),false);});
test('duplicate and older signed delivery events remain unreconciled provider reports',()=>{const current=signed(event('DELIVERED'));const older=signed({...event('COMPLETE'),eventTime:'2025-01-01T12:00:00Z'});const first=verify(current);assert.deepEqual(verify(current),first);for(const r of [first,verify(current),verify(older)]){assert.equal(r.providerReportedDelivery,true);assert.equal(r.deliveryVerified,false);assert.equal(r.reconciliationRequired,true);}assert.equal(verify(older).eventTime,'2025-01-01T12:00:00Z');});
test('raw payload signature covers exact bytes with explicitly selected encoding',()=>{for(const encoding of ['hex','base64']){const s=signed(event(),encoding);assert.ok(verify(s));assert.equal(verify({...s,rawPayload:Buffer.concat([s.rawPayload,Buffer.from(' ')])}),null);}assert.equal(verify({...signed(),signatureEncoding:undefined}),null);assert.equal(verify({...signed(),signature:'sha256='+signed().signature}),null);});
test('signed but foreign source/order/document or unsupported event/status rejects',()=>{for(const value of [{...signed(),expectedExternalOrderId:'other'},{...signed(),expectedSenderCode:'other'},{...signed(),expectedDocumentId:'other'},signed({...event(),event:'unknown'}),signed(event('UNKNOWN')),{...signed(),rawPayload:new Uint8Array(128_001)},{...signed(),secret:''}])assert.equal(verify(value),null);});
